const ACCESS_TOKEN_TTL = "7d";
const PASSWORD_RESET_TOKEN_TTL_MINUTES = 60;
const ACCOUNT_LOCK_WINDOW_MINUTES = 15;
const ACCOUNT_LOCK_MAX_ATTEMPTS = 5;

export {
  ACCESS_TOKEN_TTL,
  PASSWORD_RESET_TOKEN_TTL_MINUTES,
  ACCOUNT_LOCK_WINDOW_MINUTES,
  ACCOUNT_LOCK_MAX_ATTEMPTS
};
